# Currently broken and leaving be for now
# 
# name: Generate D2 diagrams 
# run-name: ${{ github.actor }} is building D2 diagrams representing Stripe scenarios. 
# on: 
  # workflow_dispatch:
  # push:
# jobs:
#   build-d2:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out repository code
#         uses: actions/checkout@v3

#       - name: Set up Go
#         uses: actions/setup-go@v3
#         with:
#           go-version: 1.19
      
#       - name: Install D2
#         run: |
#           go install oss.terrastruct.com/d2@latest
      
#       - name: Generate D2 images
#         run: d2 --layout dagre src/**/*.d2